/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedLandingIndexRouteImport } from './routes/_authenticated/landing/index'
import { Route as AuthenticatedLandingBookingsRouteImport } from './routes/_authenticated/landing/bookings'
import { Route as AuthenticatedLandingLeadsRouteImport } from './routes/_authenticated/landing/leads'
import { Route as AuthenticatedLandingSettingsRouteImport } from './routes/_authenticated/landing/settings'
import { Route as AuthenticatedLandingVslRouteImport } from './routes/_authenticated/landing/vsl'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedSprintsIndexRouteImport } from './routes/_authenticated/sprints/index'
import { Route as AuthenticatedSprintsSprintIdRouteImport } from './routes/_authenticated/sprints/$sprintId'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as AuthenticatedWebsiteIndexRouteImport } from './routes/_authenticated/website/index'
import { Route as AuthenticatedWebsiteDiagnoseRouteImport } from './routes/_authenticated/website/diagnose'
import { Route as AuthenticatedWebsiteDiagnoseLeadsRouteImport } from './routes/_authenticated/website/diagnose-leads'
import { Route as AuthenticatedWebsiteLeadsRouteImport } from './routes/_authenticated/website/leads'
import { Route as AuthenticatedWebsiteProjectsRouteImport } from './routes/_authenticated/website/projects'
import { Route as AuthenticatedWebsiteSectionsRouteImport } from './routes/_authenticated/website/sections'
import { Route as AuthenticatedWebsiteSettingsRouteImport } from './routes/_authenticated/website/settings'
import { Route as AuthenticatedWebsiteTeamRouteImport } from './routes/_authenticated/website/team'
import { Route as AuthenticatedWebsiteTestimonialsRouteImport } from './routes/_authenticated/website/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingIndexRoute =
  AuthenticatedLandingIndexRouteImport.update({
    id: '/landing/',
    path: '/landing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingBookingsRoute =
  AuthenticatedLandingBookingsRouteImport.update({
    id: '/landing/bookings',
    path: '/landing/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingLeadsRoute =
  AuthenticatedLandingLeadsRouteImport.update({
    id: '/landing/leads',
    path: '/landing/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingSettingsRoute =
  AuthenticatedLandingSettingsRouteImport.update({
    id: '/landing/settings',
    path: '/landing/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingVslRoute = AuthenticatedLandingVslRouteImport.update({
  id: '/landing/vsl',
  path: '/landing/vsl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprintsIndexRoute =
  AuthenticatedSprintsIndexRouteImport.update({
    id: '/sprints/',
    path: '/sprints/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSprintsSprintIdRoute =
  AuthenticatedSprintsSprintIdRouteImport.update({
    id: '/sprints/$sprintId',
    path: '/sprints/$sprintId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteIndexRoute =
  AuthenticatedWebsiteIndexRouteImport.update({
    id: '/website/',
    path: '/website/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteDiagnoseRoute =
  AuthenticatedWebsiteDiagnoseRouteImport.update({
    id: '/website/diagnose',
    path: '/website/diagnose',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteDiagnoseLeadsRoute =
  AuthenticatedWebsiteDiagnoseLeadsRouteImport.update({
    id: '/website/diagnose-leads',
    path: '/website/diagnose-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteLeadsRoute =
  AuthenticatedWebsiteLeadsRouteImport.update({
    id: '/website/leads',
    path: '/website/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteProjectsRoute =
  AuthenticatedWebsiteProjectsRouteImport.update({
    id: '/website/projects',
    path: '/website/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteSectionsRoute =
  AuthenticatedWebsiteSectionsRouteImport.update({
    id: '/website/sections',
    path: '/website/sections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteSettingsRoute =
  AuthenticatedWebsiteSettingsRouteImport.update({
    id: '/website/settings',
    path: '/website/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteTeamRoute =
  AuthenticatedWebsiteTeamRouteImport.update({
    id: '/website/team',
    path: '/website/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteTestimonialsRoute =
  AuthenticatedWebsiteTestimonialsRouteImport.update({
    id: '/website/testimonials',
    path: '/website/testimonials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/landing/bookings': typeof AuthenticatedLandingBookingsRoute
  '/landing/leads': typeof AuthenticatedLandingLeadsRoute
  '/landing/settings': typeof AuthenticatedLandingSettingsRoute
  '/landing/vsl': typeof AuthenticatedLandingVslRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/sprints/$sprintId': typeof AuthenticatedSprintsSprintIdRoute
  '/website/diagnose': typeof AuthenticatedWebsiteDiagnoseRoute
  '/website/diagnose-leads': typeof AuthenticatedWebsiteDiagnoseLeadsRoute
  '/website/leads': typeof AuthenticatedWebsiteLeadsRoute
  '/website/projects': typeof AuthenticatedWebsiteProjectsRoute
  '/website/sections': typeof AuthenticatedWebsiteSectionsRoute
  '/website/settings': typeof AuthenticatedWebsiteSettingsRoute
  '/website/team': typeof AuthenticatedWebsiteTeamRoute
  '/website/testimonials': typeof AuthenticatedWebsiteTestimonialsRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/landing/': typeof AuthenticatedLandingIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/sprints/': typeof AuthenticatedSprintsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/website/': typeof AuthenticatedWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/landing/bookings': typeof AuthenticatedLandingBookingsRoute
  '/landing/leads': typeof AuthenticatedLandingLeadsRoute
  '/landing/settings': typeof AuthenticatedLandingSettingsRoute
  '/landing/vsl': typeof AuthenticatedLandingVslRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/sprints/$sprintId': typeof AuthenticatedSprintsSprintIdRoute
  '/website/diagnose': typeof AuthenticatedWebsiteDiagnoseRoute
  '/website/diagnose-leads': typeof AuthenticatedWebsiteDiagnoseLeadsRoute
  '/website/leads': typeof AuthenticatedWebsiteLeadsRoute
  '/website/projects': typeof AuthenticatedWebsiteProjectsRoute
  '/website/sections': typeof AuthenticatedWebsiteSectionsRoute
  '/website/settings': typeof AuthenticatedWebsiteSettingsRoute
  '/website/team': typeof AuthenticatedWebsiteTeamRoute
  '/website/testimonials': typeof AuthenticatedWebsiteTestimonialsRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/landing': typeof AuthenticatedLandingIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/sprints': typeof AuthenticatedSprintsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/website': typeof AuthenticatedWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/landing/bookings': typeof AuthenticatedLandingBookingsRoute
  '/_authenticated/landing/leads': typeof AuthenticatedLandingLeadsRoute
  '/_authenticated/landing/settings': typeof AuthenticatedLandingSettingsRoute
  '/_authenticated/landing/vsl': typeof AuthenticatedLandingVslRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/sprints/$sprintId': typeof AuthenticatedSprintsSprintIdRoute
  '/_authenticated/website/diagnose': typeof AuthenticatedWebsiteDiagnoseRoute
  '/_authenticated/website/diagnose-leads': typeof AuthenticatedWebsiteDiagnoseLeadsRoute
  '/_authenticated/website/leads': typeof AuthenticatedWebsiteLeadsRoute
  '/_authenticated/website/projects': typeof AuthenticatedWebsiteProjectsRoute
  '/_authenticated/website/sections': typeof AuthenticatedWebsiteSectionsRoute
  '/_authenticated/website/settings': typeof AuthenticatedWebsiteSettingsRoute
  '/_authenticated/website/team': typeof AuthenticatedWebsiteTeamRoute
  '/_authenticated/website/testimonials': typeof AuthenticatedWebsiteTestimonialsRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/landing/': typeof AuthenticatedLandingIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/sprints/': typeof AuthenticatedSprintsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/website/': typeof AuthenticatedWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/overview'
    | '/landing/bookings'
    | '/landing/leads'
    | '/landing/settings'
    | '/landing/vsl'
    | '/projects/$projectId'
    | '/sprints/$sprintId'
    | '/website/diagnose'
    | '/website/diagnose-leads'
    | '/website/leads'
    | '/website/projects'
    | '/website/sections'
    | '/website/settings'
    | '/website/team'
    | '/website/testimonials'
    | '/clients/'
    | '/finance/'
    | '/landing/'
    | '/projects/'
    | '/sprints/'
    | '/tasks/'
    | '/team/'
    | '/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/overview'
    | '/landing/bookings'
    | '/landing/leads'
    | '/landing/settings'
    | '/landing/vsl'
    | '/projects/$projectId'
    | '/sprints/$sprintId'
    | '/website/diagnose'
    | '/website/diagnose-leads'
    | '/website/leads'
    | '/website/projects'
    | '/website/sections'
    | '/website/settings'
    | '/website/team'
    | '/website/testimonials'
    | '/clients'
    | '/finance'
    | '/landing'
    | '/projects'
    | '/sprints'
    | '/tasks'
    | '/team'
    | '/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/overview'
    | '/_authenticated/landing/bookings'
    | '/_authenticated/landing/leads'
    | '/_authenticated/landing/settings'
    | '/_authenticated/landing/vsl'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/sprints/$sprintId'
    | '/_authenticated/website/diagnose'
    | '/_authenticated/website/diagnose-leads'
    | '/_authenticated/website/leads'
    | '/_authenticated/website/projects'
    | '/_authenticated/website/sections'
    | '/_authenticated/website/settings'
    | '/_authenticated/website/team'
    | '/_authenticated/website/testimonials'
    | '/_authenticated/clients/'
    | '/_authenticated/finance/'
    | '/_authenticated/landing/'
    | '/_authenticated/projects/'
    | '/_authenticated/sprints/'
    | '/_authenticated/tasks/'
    | '/_authenticated/team/'
    | '/_authenticated/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/': {
      id: '/_authenticated/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof AuthenticatedLandingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/bookings': {
      id: '/_authenticated/landing/bookings'
      path: '/landing/bookings'
      fullPath: '/landing/bookings'
      preLoaderRoute: typeof AuthenticatedLandingBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/leads': {
      id: '/_authenticated/landing/leads'
      path: '/landing/leads'
      fullPath: '/landing/leads'
      preLoaderRoute: typeof AuthenticatedLandingLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/settings': {
      id: '/_authenticated/landing/settings'
      path: '/landing/settings'
      fullPath: '/landing/settings'
      preLoaderRoute: typeof AuthenticatedLandingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/vsl': {
      id: '/_authenticated/landing/vsl'
      path: '/landing/vsl'
      fullPath: '/landing/vsl'
      preLoaderRoute: typeof AuthenticatedLandingVslRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprints/': {
      id: '/_authenticated/sprints/'
      path: '/sprints'
      fullPath: '/sprints/'
      preLoaderRoute: typeof AuthenticatedSprintsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sprints/$sprintId': {
      id: '/_authenticated/sprints/$sprintId'
      path: '/sprints/$sprintId'
      fullPath: '/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/': {
      id: '/_authenticated/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof AuthenticatedWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/diagnose': {
      id: '/_authenticated/website/diagnose'
      path: '/website/diagnose'
      fullPath: '/website/diagnose'
      preLoaderRoute: typeof AuthenticatedWebsiteDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/diagnose-leads': {
      id: '/_authenticated/website/diagnose-leads'
      path: '/website/diagnose-leads'
      fullPath: '/website/diagnose-leads'
      preLoaderRoute: typeof AuthenticatedWebsiteDiagnoseLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/leads': {
      id: '/_authenticated/website/leads'
      path: '/website/leads'
      fullPath: '/website/leads'
      preLoaderRoute: typeof AuthenticatedWebsiteLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/projects': {
      id: '/_authenticated/website/projects'
      path: '/website/projects'
      fullPath: '/website/projects'
      preLoaderRoute: typeof AuthenticatedWebsiteProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/sections': {
      id: '/_authenticated/website/sections'
      path: '/website/sections'
      fullPath: '/website/sections'
      preLoaderRoute: typeof AuthenticatedWebsiteSectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/settings': {
      id: '/_authenticated/website/settings'
      path: '/website/settings'
      fullPath: '/website/settings'
      preLoaderRoute: typeof AuthenticatedWebsiteSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/team': {
      id: '/_authenticated/website/team'
      path: '/website/team'
      fullPath: '/website/team'
      preLoaderRoute: typeof AuthenticatedWebsiteTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/testimonials': {
      id: '/_authenticated/website/testimonials'
      path: '/website/testimonials'
      fullPath: '/website/testimonials'
      preLoaderRoute: typeof AuthenticatedWebsiteTestimonialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedLandingBookingsRoute: typeof AuthenticatedLandingBookingsRoute
  AuthenticatedLandingLeadsRoute: typeof AuthenticatedLandingLeadsRoute
  AuthenticatedLandingSettingsRoute: typeof AuthenticatedLandingSettingsRoute
  AuthenticatedLandingVslRoute: typeof AuthenticatedLandingVslRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedSprintsSprintIdRoute: typeof AuthenticatedSprintsSprintIdRoute
  AuthenticatedWebsiteDiagnoseRoute: typeof AuthenticatedWebsiteDiagnoseRoute
  AuthenticatedWebsiteDiagnoseLeadsRoute: typeof AuthenticatedWebsiteDiagnoseLeadsRoute
  AuthenticatedWebsiteLeadsRoute: typeof AuthenticatedWebsiteLeadsRoute
  AuthenticatedWebsiteProjectsRoute: typeof AuthenticatedWebsiteProjectsRoute
  AuthenticatedWebsiteSectionsRoute: typeof AuthenticatedWebsiteSectionsRoute
  AuthenticatedWebsiteSettingsRoute: typeof AuthenticatedWebsiteSettingsRoute
  AuthenticatedWebsiteTeamRoute: typeof AuthenticatedWebsiteTeamRoute
  AuthenticatedWebsiteTestimonialsRoute: typeof AuthenticatedWebsiteTestimonialsRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedLandingIndexRoute: typeof AuthenticatedLandingIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSprintsIndexRoute: typeof AuthenticatedSprintsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
  AuthenticatedWebsiteIndexRoute: typeof AuthenticatedWebsiteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedLandingBookingsRoute: AuthenticatedLandingBookingsRoute,
  AuthenticatedLandingLeadsRoute: AuthenticatedLandingLeadsRoute,
  AuthenticatedLandingSettingsRoute: AuthenticatedLandingSettingsRoute,
  AuthenticatedLandingVslRoute: AuthenticatedLandingVslRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedSprintsSprintIdRoute: AuthenticatedSprintsSprintIdRoute,
  AuthenticatedWebsiteDiagnoseRoute: AuthenticatedWebsiteDiagnoseRoute,
  AuthenticatedWebsiteDiagnoseLeadsRoute:
    AuthenticatedWebsiteDiagnoseLeadsRoute,
  AuthenticatedWebsiteLeadsRoute: AuthenticatedWebsiteLeadsRoute,
  AuthenticatedWebsiteProjectsRoute: AuthenticatedWebsiteProjectsRoute,
  AuthenticatedWebsiteSectionsRoute: AuthenticatedWebsiteSectionsRoute,
  AuthenticatedWebsiteSettingsRoute: AuthenticatedWebsiteSettingsRoute,
  AuthenticatedWebsiteTeamRoute: AuthenticatedWebsiteTeamRoute,
  AuthenticatedWebsiteTestimonialsRoute: AuthenticatedWebsiteTestimonialsRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedLandingIndexRoute: AuthenticatedLandingIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSprintsIndexRoute: AuthenticatedSprintsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
  AuthenticatedWebsiteIndexRoute: AuthenticatedWebsiteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
